### ISSUE TITLE
In multi user view add possibility to see online time and big game picture

### ISSUE THREAD

**Issue by tekgator** [Kibibit/kb-steam-card#3]
It would be great to still have the possibility to see the online time of a user. I suggest a pop up card where the time as well as the large game picture is displayed. Alternativly the default steam sensor card could also be option.

![image](https://user-images.githubusercontent.com/11077551/95179665-3d180900-07c1-11eb-9481-950d57db6d2f.png)

**Comment by thatkookooguy** [comment]
Sure! sounds like a good idea. what exactly did you think ? when clicking a user row a pop up opens with that user's details?

**Comment by tekgator** [comment]
Yes basically that was exactly my thought... 👍

**Comment by tekgator** [comment]
Works perfectly fine! Thank you...
