### ISSUE TITLE
readme - Prerequisites

### ISSUE THREAD

**Issue by fpschrisiom** [Kibibit/kb-steam-card#4]
Hi, please could you update the readme, not 100% clear for new users:

Prerequisites

You need at least one steam integration to use this card.
https://www.home-assistant.io/integrations/steam_online/ 

That took me minutes to setup and the card is brilliant, thanks for your work on this.

**Comment by thatkookooguy** [comment]
oh ofc! sorry I missed that! glad you like the card! :-)
